# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:        
  test-addon-with-clusters:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        #ersion: ${{ fromJson(needs.find-supported-versions.outputs.versions) }}
        version: [1.28,1.29]
    outputs:
      test: ${{ steps.test1.outputs.test }}
    env:
      K8S_VERSION: ${{ matrix.version }}
      FLCENV_PREFIX: dynatrace-operator-addon-test-
    steps:
      - name: Test1
        id: test1
        run: |
          echo "loc1" >> "${RUNNER_TEMP}/test.txt"
          echo test="Matrix step $K8S_VERSION." >> $GITHUB_OUTPUT
          printenv
          cat $GITHUB_OUTPUT

  create_release:
    needs: test-addon-with-clusters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Test
        run: |
          printenv
          echo "Release step."
          echo ${{ needs.test-addon-with-clusters.outputs.test }}
          echo ${{ fromJson(needs.test-addon-with-clusters.outputs) }}
          echo ${{ needs.test-addon-with-clusters[0] }}
          echo ${{ needs.test-addon-with-clusters }}
          printenv
          cat $GITHUB_OUTPUT
